unstable_features = true
newline_style = "Unix"
group_imports = "StdExternalCrate"
wrap_comments = true
fn_args_layout = "compressed"
force_multiline_blocks = true
format_strings = true
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true
chain_width = 60

