[package]
name = "cargo-check-tip"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.15.2"
codespan-reporting = "0.11.1"
colored = "2.0.0"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_regex = "1.1.0"
